### ISSUE TITLE
Why is filtering directories disabled?

### ISSUE THREAD

**Issue by evanbennett** [rgcottrell/sbt-filter#1] opened 2014-08-05 10:53 UTC
I am using this plugin to filter Javascript and CSS files in subfolders that are used to generate the files that are used by my system.  I noticed that the empty subfolders still exist in the 'target/web/stage/public' folder and tried to update the includeFilter to remove then.  I noticed that in SbtFilter.scala on line 35 there is 'f._1.isDirectory'.  This means that I cannot filter directories?

Is there a reason for this?

**Comment by rgcottrell** [comment] 2014-08-05 17:07
There's no particular reason why the directory isDirectory restriction is there. That's just the way that several of the other plugins I was looking at structured their filters.

As you note, filtering out a directory makes a lot of sense. I'll look into removing the restriction.

**Comment by magnusart** [comment] 2014-08-07 12:32
Hi, I have also noted this limitation. It would be great to be able to filter out directories.

**Comment by rgcottrell** [comment] 2014-08-07 22:00
I've update release 1.0.1 which removes the directory restriction. This will allow you to add an empty directory to the filter conditions.

I think it might also be nice to just specify a directory you wish to have filtered and have the plugin remove all files and subdirectories under it without any additional configuration. Let me think about a good way of doing this.

**Comment by magnusart** [comment] 2014-08-09 11:05
Hmm, I could not get this to work. But I see you have a test for it. Will continue to investigate, my settings looks like this:

```
  val filterSettings = Seq(
    includeFilter in filter := "*.js" || "*.css" || "*.less" || "js" || "less" || "vendor",
    // Only allow concatenated files to slip through
    excludeFilter in filter := "app.js" || "vendor.js" || "app.css"
  )
```

In my `target/web/stage` folder I have empty folder `js` and `less` after building. Those in turn have sub-folders. Could that be the issue?

Edit: I can confirm that the folder filter does not work if the folder contains other folders (or files?). Is there any syntax to allow for filtering out a folder structure and it's content? Right now I have to know all subfolders that exist so I can filter out those first.

This is my current filter

```
includeFilter in filter := "*.js" || "*.css" || "*.css.map" || "*.less" || "controllers" || "directives" || "filters" || "services" || "js" || "bootstrap-less" || "mixins" || "less" || "vendor"
excludeFilter in filter := "app.js" || "vendor.js" || "app.css"
```

**Comment by evanbennett** [comment] 2014-08-12 11:12
I have been thinking about a nicer way to filter a directory and its contents (including sub-directories).

Currently, I am filtering 'working' directories in 'javascripts' and 'stylesheets'.

``` scala
includeFilter in filter := new SimpleFileFilter(file => file.getParentFile.getName == "working" || file.getName == "working")
```

This works fine assuming there are no sub-directories.

I think you could create a setting like 'includeFilter', something like 'filterDirectory'. Then in SbtFilter.scala on line 35, you could append something equivalent to '|| !filterDirectory.value(f._2)'. This would make the filter writing in build.sbt much simpler, as it processes a 'String' containing the path relative to 'webTarget', instead of a 'File'. e.g. 

``` scala
filterDirectory in filter := { path: String => path.startsWith("javascripts\working\") }
```

What do you think?

**Comment by specterstudios** [comment] 2014-12-11 08:52
Hi, have there been any new ideas about filtering out entire directories and their contents with this plugin? I'm also in need of this functionality.

For now, I am thinking about just chaining directories like:
includeFilter in filter := new SimpleFileFilter(file => file.getParentFile.getName == "assets" || file.getParentFile.getParentFile.getName == "assets")

to handle subdirectories.

Maybe we can just write a FileFilter class to simplify this kind of directory / sub-directory filtering.

**Comment by evanbennett** [comment] 2017-10-24 06:09
I have submitted pull request #2 which includes a `PathFilter` to provide a way of achieving this.

**Comment by eximius313** [comment] 2017-10-30 00:34
@rgcottrell could you please merge this PR?

**Comment by rgcottrell** [comment] 2017-11-02 03:41
Sorry I missed the notification about the PR. Without having a reviewer assigned, the request doesn't show up in GitHub's "Pull requests" tab. It's now been merged.

**Comment by eximius313** [comment] 2017-11-02 11:02
Thank you! Do you plan to release new version of ```sbt-filter```?

**Closed as completed** 2018-03-07 02:44 UTC
